development:
  adapter: postgresql
  database: uptospeed
  username: uptospeed
test:
  adapter: postgresql
  database: uptospeed_test
  username: uptospeed
production:
  adapter: postgresql
  database: uptospeed
  username: uptospeed